# Generated by Django 4.0.6 on 2022-07-14 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(choices=[('FL', 'FootLocker'), ('G', 'GOAT'), ('STX', 'STOCKX'), ('FL', 'Finish-line'), ('C', 'Champs'), ('N', 'Nike.com')], default=('FL', 'FootLocker'), max_length=5)),
                ('in_stock', models.BooleanField()),
                ('no_instock', models.IntegerField()),
                ('kick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.kick')),
            ],
        ),
    ]
